require_relative './config/environment'
require 'sinatra/activerecord/rake'
# require 'rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "Say hello to everyone"
task :hello do
	puts "What's up everyone"
end